<?php

return [
    'indicators' => [
    	'time_frame' => [
    		'1m' => '1m',
			'3m' => '3m',
			'5m' => '5m',
			'10m' => '10m',
			'15m' => '15m',
			'30m' => '30m',
			'1h' => '1h',
			'2h' => '2h',
			'3h' => '3h',
			'4h' => '4h',
			'6h' => '6h',
			'1d' => '1d',
			'1w' => '1w',
    	],
    	'rsi' => [
    		'bearish_div' => 'Bearish Div',
			'bullish_div' => 'Bullish Div',
			'trend_line' => 'Trend Line',
			'overbought_70' => 'Overbought 70+',
			'overbought_80' => 'Overbought 80+',
			'overbought_90' => 'Overbought 90+',
			'oversold_30' => 'Oversold 30-',
			'oversold_20' => 'Oversold 20-',
			'oversold_10' => 'Oversold 10-',
    	],
    	'fib' => [
    		'.0' => '0',
			'.236' => '.236',
			'.382' => '.382',
			'.5' => '.5',
			'.618' => '.618',
			'.65' => '.65',
			'.786' => '.786',
			'.1' => '1',
    	],
    	'ew' => [
    		'1' => '1',
			'2' => '2',
			'3' => '3',
			'4' => '4',
			'5' => '5',
			'a' => 'A',
			'b' => 'B',
			'c' => 'C',
			'd' => 'D',
			'e' => 'E',
    	],
    	'macd' => [
    		'histogram_bearish' => 'Histogram Bearish',
			'histogram_bullish' => 'Histogram Bullish',
			'crossover_down' => 'Crossover Down',
			'crossover_up' => 'Crossover Up',
    	],
    	'trend_lines' => [
    		'ascending_channel' => 'Ascending Channel',
			'descending_channel' => 'Descending Channel',
			'ascending_triangle' => 'Ascending Triangle',
			'descending_triangle' => 'Descending Triangle',
			'symmetric_triangle' => 'Symmetric Triangle',
			'bull_flag' => 'Bull Flag',
			'bear_flag' => 'Bear Flag',
			'bear_wedge' => 'Bear Wedge',
			'bull_wedge' => 'Bull Wedge',
			'support_line' => 'Support Line',
			'resistance_line' => 'Resistance Line',
    	],
    	'ema' => [
    		'55_crossover' => '55 Crossover',
			'100_crossover' => '100 Crossover',
			'200_crossover' => '200 Crossover',
			'13_support' => '13 Support',
			'21_support' => '21 Support',
			'55_support' => '55 Support',
			'100_support' => '100 Support',
			'200_support' => '200 Support',
			'13_resistance' => '13 Resistance',
			'21_resistance' => '21 Resistance',
			'55_resistance' => '55 Resistance',
			'100_resistance' => '100 Resistance',
			'200_resistance' => '200 Resistance',
    	],
    	'candles' => [
			'bearish' => 'Bearish',
			'bullish' => 'Bullish',
    	],
    	'price_action' => [
			'bearish' => 'Bearish',
			'bullish' => 'Bullish',
    	],
    	'order_book' => [
    		'bearish' => 'Bearish',
			'bullish' => 'Bullish',
    	],
    	'fundamental' => [
    		'bullish_news' => 'Bullish News',
    		'bearish_news' => 'Bearish News',
    		'bullish_hype' => 'Bullish Hype',
    		'bearish_hype' => 'Bearish Hype',
    	]
    ],

    'indicator_names' => [
    	'time_frame' => 'Time Frame',
    	'rsi' => 'RSI',
    	'fib' => 'FIB',
    	'ew' => 'EW',
    	'macd' => 'MACD',
    	'trend_lines' => 'Trend Lines',
    	'ema' => 'EMA',
    	'candles' => 'Candles',
    	'price_action' => 'Price Action',
    	'order_book' => 'Order Book',
    	'fundamental' => 'Fundamental',
    ],
];